services:
  painel-web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./db:/app/db
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./db/avisos.db
    env_file:
      - .env
